### ISSUE TITLE
Add SSL support.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#1]
To prevent Firefox from complaining add sslify: https://github.com/kennethreitz/flask-sslify

Usage:
```
from flask import Flask
from flask_sslify import SSLify

app = Flask(__name__)
sslify = SSLify(app)
```

**Comment by elthran** [comment]
I found the bug and will push a solution when I get home. SSL is fully enabled and working, but it's just temporarily disabled when debug mode is on. I will adjust it so that running on Pythonanywhere automatically disables debug.

**Comment by klondikemarlen** [comment]
Cool :)
