### ISSUE TITLE
Crash on attempted vote

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#10]
I tried to vote for myself and the server crashed.

See attached error log:

<details>
    <summary>Error Log snippet</summary>
    <p>

> 2018-11-16 16:06:30,864: OSError: write error
> 2018-11-16 16:20:29,463: Error running WSGI application
> 2018-11-16 16:20:29,483: sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2013, 'Lost connection to MySQL server during query') [SQL: 'SELECT user.id AS user_id, user.date_created AS user_date_created, user.date_modified AS user_date_modified, user.name AS user_name, user.email AS user_email, user.password_hash AS user_password_hash, user.phone AS user_phone, user.session_id AS user_session_id, user.is_authenticated AS user_is_authenticated, user.is_active AS user_is_active, user.is_anonymous AS user_is_anonymous \nFROM user \nWHERE user.id = %s'] [parameters: (3,)] (Background on this error at: http://sqlalche.me/e/e3q8)
> 2018-11-16 16:20:29,484:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
> 2018-11-16 16:20:29,484:     return self.wsgi_app(environ, start_response)
> 2018-11-16 16:20:29,484: 
> 2018-11-16 16:20:29,484:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
> 2018-11-16 16:20:29,484:     response = self.handle_exception(e)
> 2018-11-16 16:20:29,485: 
> 2018-11-16 16:20:29,485:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
> 2018-11-16 16:20:29,485:     reraise(exc_type, exc_value, tb)
> 2018-11-16 16:20:29,485: 
> 2018-11-16 16:20:29,485:   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> 2018-11-16 16:20:29,485:     raise value
> 2018-11-16 16:20:29,486: 
> 2018-11-16 16:20:29,486:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> 2018-11-16 16:20:29,486:     response = self.full_dispatch_request()
> 2018-11-16 16:20:29,486: 
> 2018-11-16 16:20:29,486:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
> 2018-11-16 16:20:29,487:     rv = self.handle_user_exception(e)
> 2018-11-16 16:20:29,487: 
> 2018-11-16 16:20:29,487:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
> 2018-11-16 16:20:29,487:     reraise(exc_type, exc_value, tb)
> 2018-11-16 16:20:29,487: 
> 2018-11-16 16:20:29,487:   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
> 2018-11-16 16:20:29,488:     raise value
> 2018-11-16 16:20:29,488: 
> 2018-11-16 16:20:29,488:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
> 2018-11-16 16:20:29,488:     rv = self.dispatch_request()
> 2018-11-16 16:20:29,488: 
> 2018-11-16 16:20:29,488:   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
> 2018-11-16 16:20:29,489:     return self.view_functions[rule.endpoint](**req.view_args)
> 2018-11-16 16:20:29,489: 
> 2018-11-16 16:20:29,489:   File "/home/undyingkingdoms/UndyingKingdoms/undyingkingdoms/routes/gameplay/kingdom.py", line 11, in kingdom
> 2018-11-16 16:20:29,489:     form = VoteForm(vote=current_user.county.vote)
> 2018-11-16 16:20:29,489: 
> 2018-11-16 16:20:29,489:   File "/usr/lib/python3.6/site-packages/werkzeug/local.py", line 347, in __getattr__
> 2018-11-16 16:20:29,490:     return getattr(self._get_current_object(), name)
> 2018-11-16 16:20:29,490: 
> 2018-11-16 16:20:29,490:   File "/usr/lib/python3.6/site-packages/werkzeug/local.py", line 306, in _get_current_object
> 2018-11-16 16:20:29,490:     return self.__local()
> 2018-11-16 16:20:29,490: 
> 2018-11-16 16:20:29,491:   File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 26, in <lambda>
> 2018-11-16 16:20:29,491:     current_user = LocalProxy(lambda: _get_user())
> 2018-11-16 16:20:29,491: 
> 2018-11-16 16:20:29,491:   File "/usr/lib/python3.6/site-packages/flask_login/utils.py", line 335, in _get_user
> 2018-11-16 16:20:29,491:     current_app.login_manager._load_user()
> 2018-11-16 16:20:29,492: 
> 2018-11-16 16:20:29,492:   File "/usr/lib/python3.6/site-packages/flask_login/login_manager.py", line 359, in _load_user
> 2018-11-16 16:20:29,492:     return self.reload_user()
> 2018-11-16 16:20:29,492: 
> 2018-11-16 16:20:29,492:   File "/usr/lib/python3.6/site-packages/flask_login/login_manager.py", line 321, in reload_user
> 2018-11-16 16:20:29,492:     user = self.user_callback(user_id)
> 2018-11-16 16:20:29,493: 
> 2018-11-16 16:20:29,493:   File "/home/undyingkingdoms/UndyingKingdoms/undyingkingdoms/__init__.py", line 78, in load_user
> 2018-11-16 16:20:29,493:     return User.query.get(this_id)
> 2018-11-16 16:20:29,493: 
> 2018-11-16 16:20:29,493:   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 923, in get
> 2018-11-16 16:20:29,493:     ident, loading.load_on_pk_identity)
> 2018-11-16 16:20:29,494: 
> 2018-11-16 16:20:29,494:   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1006, in _get_impl
> 2018-11-16 16:20:29,494:     return db_load_fn(self, primary_key_identity)
> 2018-11-16 16:20:29,494: 
> 2018-11-16 16:20:29,494:   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 250, in load_on_pk_identity
> 2018-11-16 16:20:29,494:     return q.one()
> 2018-11-16 16:20:29,495: 
> 2018-11-16 16:20:29,495:   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2947, in one
> 2018-11-16 16:20:29,495:     ret = self.one_or_none()
> 2018-11-16 16:20:29,495: 
> 2018-11-16 16:20:29,495:   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2917, in one_or_none
> 2018-11-16 16:20:29,496:     ret = list(self)
> 2018-11-16 16:20:29,496: 
> 2018-11-16 16:20:29,496:   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
> 2018-11-16 16:20:29,496:     return self._execute_and_instances(context)
> 2018-11-16 16:20:29,496: 
> 2018-11-16 16:20:29,496:   File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
> 2018-11-16 16:20:29,497:     result = conn.execute(querycontext.statement, self._params)
> 2018-11-16 16:20:29,497: 
> 2018-11-16 16:20:29,497:   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
> 2018-11-16 16:20:29,497:     return meth(self, multiparams, params)
> 2018-11-16 16:20:29,497: 
> 2018-11-16 16:20:29,498:   File "/usr/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
> 2018-11-16 16:20:29,498:     return connection._execute_clauseelement(self, multiparams, params)
> 2018-11-16 16:20:29,498: 
> 2018-11-16 16:20:29,498:   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
> 2018-11-16 16:20:29,498:     compiled_sql, distilled_params
> 2018-11-16 16:20:29,498: 
> 2018-11-16 16:20:29,499:   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
> 2018-11-16 16:20:29,499:     context)
> 2018-11-16 16:20:29,463: Error running WSGI application
> 2018-11-16 16:20:29,499: 
> 2018-11-16 16:20:29,499:   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
> 2018-11-16 16:20:29,499:     exc_info
> 2018-11-16 16:20:29,499: 
> 2018-11-16 16:20:29,500:   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
> 2018-11-16 16:20:29,500:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
> 2018-11-16 16:20:29,500: 
> 2018-11-16 16:20:29,500:   File "/usr/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 248, in reraise
> 2018-11-16 16:20:29,500:     raise value.with_traceback(tb)
> 2018-11-16 16:20:29,500: 
> 2018-11-16 16:20:29,501:   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
> 2018-11-16 16:20:29,501:     context)
> 2018-11-16 16:20:29,501: 
> 2018-11-16 16:20:29,501:   File "/usr/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
> 2018-11-16 16:20:29,501:     cursor.execute(statement, parameters)
> 2018-11-16 16:20:29,502: 
> 2018-11-16 16:20:29,502:   File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
> 2018-11-16 16:20:29,502:     self.errorhandler(self, exc, value)
> 2018-11-16 16:20:29,502: 
> 2018-11-16 16:20:29,502:   File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
> 2018-11-16 16:20:29,502:     raise errorvalue
> 2018-11-16 16:20:29,503: 
> 2018-11-16 16:20:29,503:   File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
> 2018-11-16 16:20:29,503:     res = self._query(query)
> 2018-11-16 16:20:29,503: 
> 2018-11-16 16:20:29,503:   File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 412, in _query
> 2018-11-16 16:20:29,504:     rowcount = self._do_query(q)
> 2018-11-16 16:20:29,504: 
> 2018-11-16 16:20:29,504:   File "/usr/lib/python3.6/site-packages/MySQLdb/cursors.py", line 375, in _do_query
> 2018-11-16 16:20:29,504:     db.query(q)
> 2018-11-16 16:20:29,504: 
> 2018-11-16 16:20:29,504:   File "/usr/lib/python3.6/site-packages/MySQLdb/connections.py", line 276, in query
> 2018-11-16 16:20:29,505:     _mysql.connection.query(self, query)
    </p>
</details>

**Comment by klondikemarlen** [comment]
I honestly have no idea what this might be caused by though this might be important:
"user.is_anonymous AS user_is_anonymous"

It might be that the current user isn't logged in correctly and it is crashing because I am voting as anonymous?

**Comment by elthran** [comment]
Yes this is nothing to do with voting if I'm right. It means that you were logged out of the session and tried to perform an action, but Flask login thought you were not authenticated. However, if you refresh the page then Flask should relogin automatically. Not sure what's causing this; it seems to be pythonanywhere related.

**Comment by elthran** [comment]
I'm going to close this issue and move any info to the other ticket, since this is basically a duplicate ticket and github doesnt let you mark duplicates the proper way
