### ISSUE TITLE
My theives are returning instantly.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#101]
After I send out my thieves I can update the report immediately even though it says it will take 25 days for them to return.

**Comment by elthran** [comment]
That shouldn't happen. I will need to try and replicate the bug to see what's causing it.

**Comment by klondikemarlen** [comment]
Seems to be less obvious than I thought. It only occurred when I went to update a report I had just made. When I sent thieves to report on a different county they stayed away. So maybe only Update Report is broken. Or only Update Report on the county you sent the thieves.

**Comment by klondikemarlen** [comment]
I have no idea what is going on with this one. Sometimes my thieves return instantly for quite some time; then suddenly they don't.

**Comment by elthran** [comment]
I'll try to fix it this week. If you ever find out a consistent way to replicate it, let me know :)

**Comment by klondikemarlen** [comment]
Still no idea. I didn't have it for a while then it started happening again. Now I'm back to one scout per 25 days :P

**Comment by elthran** [comment]
I did a patch which *might* have fixed this. I haven't seen this bug since then, so I will close it for now and reopen it if it comes back.
