### ISSUE TITLE
Make Thieves Report include Defensive Power.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#103]
The current thieves report doesn't let me know how strong my opponent is only how many troops they have. It would be nice if it included the Power of my opponent.

Perhaps you could have a JS running total on the Attack page too? And include the data from any relevant thieves report so you could compare.

**Comment by klondikemarlen** [comment]
Perhaps it might be better to have Thieves Report get more detailed depending on how many guilds you had instead of making it faster. The speed of reporting could be based on stables just like army return rate.

**Comment by elthran** [comment]
I like the idea of more thieves guilds equal more detail that you said. Like 1-5% gives you total troop estimate and total buildings built estimate. then 5-10% gives an estimate of each building/troop type. Something like that.

**Comment by klondikemarlen** [comment]
I don't like the percent part. I think it might be better to simply have 1-5 guilds.

**Comment by klondikemarlen** [comment]
The information in the game simply isn't that valuable.
