### ISSUE TITLE
Food production never keeps up with population growth?

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#106]
Based on my population growth to worker ratio I can never seem to build enough farms to keep up with my population growth. I have 8 farms being built at all times (I keep adding more) but if I build more houses to get more production speed I need more farms to feed the people.

![image](https://user-images.githubusercontent.com/23045206/50868633-4d3d5300-1365-11e9-9e9c-0db3005582ac.png)

**Comment by elthran** [comment]
I'll test this one locally on the weekend and try to balance it.

**Comment by klondikemarlen** [comment]
I finally managed to get ahead in food production, so this may not be as serious an issue as I though. It would be nice to widen the gap a little early game though. 

I also found that 14 grain fields was way more than I needed. I never built a single one. It would make more sense to me if grain fields produced much more than Dairy farms, but you only needed between 1-8 in the entire game.
