### ISSUE TITLE
Make create all/drop all require special argument.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#11]
This is a development feature request. I don't want your latest update to delete my local database unless I actually tell it to.

This could be implemented putting the "create/drop" section from the \_\_init__.py file in an if statement with the condition pulled from a global os level variable. os.environ.get style. You, in run.yp, do "export FLASK_RESET=true" or something.

**Comment by elthran** [comment]
Maybe I can add the drop_all/create_all to the private config? That way it never does it on the server.
