### ISSUE TITLE
Have the export code run immediately after 24 hour analytics

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#111]
When the 24 hour analytics runs and the DAU and daily aggregate tables are created, then after that immediately run the export code. And we shouldn't need a view for it anymore. Just have it as a daily automated process, so no matter what we just store each days data. It will also allow us to easily roll back to any date.

**Comment by klondikemarlen** [comment]
I could easily extend my remote cron job code to do this. But you need to test out the current version first.
