### ISSUE TITLE
Chat Room: Make discussion page auto-refresh.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#121]
Us a JS timer on the front end to pull in data from new chats.

You'll finally have to switch to API style for this one!

**Comment by klondikemarlen** [comment]
I'm going to try and use Vue.js for this ... hopefully it won't be slow like before.

**Comment by elthran** [comment]
Unless I'm mistaken, you've already done this? @klondikemarlen If so, please close it :)

**Comment by klondikemarlen** [comment]
Implemented in https://github.com/elthran/UndyingKingdoms/pull/146
