### ISSUE TITLE
Login reward should use min() not max().

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#122]
https://github.com/elthran/UndyingKingdoms/blob/0f2231bbff6c44b5efbc192989b171aff45cc47e/undyingkingdoms/routes/index/login.py#L27

The way the code currently is, every time you login and logout (1 hour apart) you 48*3 (or 4) gold.

**Comment by elthran** [comment]
You are right, it's a bug. Though for one like this it's probably less work to just push a fix rather than post a ticket about it :D

**Comment by klondikemarlen** [comment]
I was hoping you would clean up the code at the same  time.
