### ISSUE TITLE
Make scout military reveal odds of winning

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#147]
When you scout military you get troop estimates. You should also get a one sentence blurb such as "It seems the enemy is slightly stronger than you" or "They seem weak, now is a good time to attack"

**Comment by klondikemarlen** [comment]
I'm not sure about this: I think  a major flaw in most modern games is being too helpful to the user. I think there is some entertainment value from having to calculate up the strength of an enemy before attacking.

**Comment by elthran** [comment]
I fully agree... I only added this ticket because I thought you requested it.

**Comment by klondikemarlen** [comment]
It is possible that I requested it.

**Comment by elthran** [comment]
If I do anything I'd do more of a comparison to yourself rather than win chance. Ie.
"Their military appears to be much strong than ours."
"We seem to be relatively evenly matched."

But it's not really your win chance, just a global comparison. So they might be full offensive so you'd win easily, but they would counter and beat you even more easily. Also, it would be as inaccurate as your report allows.
