### ISSUE TITLE
Thief defence not reduce by active thieves.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#165]
My thief defence should be 0 (100% infiltration chance) since all my thieves are active.

![image](https://user-images.githubusercontent.com/23045206/51793794-295a7980-217b-11e9-9861-76568a7c5439.png)

**Comment by elthran** [comment]
It was 100% but it was hotfixed after the second day because 100% was really unbalanced. Now it is a range from 10%-90% based on how many thieves you have active.
