### ISSUE TITLE
Change advance_age to drop tables

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#176]
Since new buildings and modes are being added and columns are being added, it makes more sense to drop tables at the end o each week and rebuild them (that's what I did last week). The user and achievement and forum stuff doesn't get touched. Basically everything else gets wiped and rebuilt.
In models/worlds.py the function advance_age() currently does this:

`
tables = ['county', 'army', 'building', 'notification', 'expedition', 'infiltration', 'chatroom', 'message',
                  'session', 'transaction']
        for table in tables:
            helpers.empty_table(db, table)
            current_app.logger.info("Truncating table `{}`.".format(table))
`

It should instead drop these tables and then run db.create_all()
But I can't seem to get db to drop them. It only works if I manually drop each table in MySQL and then run db.create_all()
Maybe you can fix it, test it locally, and push the change :)

**Comment by klondikemarlen** [comment]
I'm pretty sure I'm dropping them that way because I couldn't drop them individually?

**Comment by elthran** [comment]
But you're not dropping them, you just deleting the rows?

**Comment by klondikemarlen** [comment]
Yeah, except it wasn't working correctly. You do that exactly :)
