### ISSUE TITLE
Fix upvotes

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#189]
Right now upvotes work perfectly. The problem is that the code is shit. When you click the upvote button it routes you to a 'upvote' page which does the upvote, then reroutes you back to the forum page you were on. It's awful code. Can you make a new branch that fixes that? Preferably uses JS so you can upvote/downvote without a page refresh, but it's not required. But definitely delete the upvote.py route...

**Comment by klondikemarlen** [comment]
Work on in https://github.com/elthran/UndyingKingdoms/tree/issue_189

**Comment by klondikemarlen** [comment]
Finished in https://github.com/elthran/UndyingKingdoms/pull/191
