### ISSUE TITLE
Update infrastructure description columns.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#196]
The description should match the race specific building type:

![image](https://user-images.githubusercontent.com/23045206/52230108-6a354b00-286b-11e9-93e3-eec7274a0934.png)

**Comment by elthran** [comment]
Yes, I just spent 5 hours on the metadata yesterday and gave up before I finished. I will do it together at work when i'm bored. Since I can run the code at work these types of tasks are perfect.
