### ISSUE TITLE
Infiltrations page should link the county you infiltrated.

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#249]
Right now it's confusing because it just says if they passed/failed. Each mission should display which county they invaded. Ideally with a link to their page.

**Comment by klondikemarlen** [comment]
I just made and issue for this too. :P I'll merge them.

**Comment by klondikemarlen** [comment]
I think the infiltrate and infiltration pages could be combined if I use an API style with a single view route.

**Comment by elthran** [comment]
Is this fixed already?
