### ISSUE TITLE
Add reply option to Inbox messages.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#282]
When I read a message in my inbox I would like to be able to reply directly to that user.
Possibly just move the message feature directly to the Inbox?

**Comment by elthran** [comment]
I'm going to assign this to you since the back-end part is simple and the bulk of this is UI. I assume you'll tackle UI one page at a time and when you get to inbox you can do this one :D

**Comment by klondikemarlen** [comment]
Fixed (you can click on the users name to reply to them).
