### ISSUE TITLE
User table is overpopulated by bots.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#283]
I suggest moving bots to their own table and referencing them all as belonging to a single user.

Bot county id are also being set manually and this could lead to conflicts if we deleted a county the last county would be overwritten by bot code.

**Comment by elthran** [comment]
Not sure how to do this. Currently at the end of each age I just run a one liner: 
delete from user where is_bot=true;

That deletes all bot stuff at the end of each age. Then I add new bots when needed. Ideally this game won't have bots in the future (or if they do they will be implemented way differently) so I wouldn't spend much time refactoring our current bots. They are literally just a place holder until we reach 9 users.

**Comment by elthran** [comment]
I'll mark it as closed for now. We can reopen it with a more concrete ticket. Right now it's just a hazy idea
