### ISSUE TITLE
Make townhall more legible

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#318]
- Embolden the username of who is chatting
- Add a small line-height increase between each line or maybe just between each new speaker
- Maybe hide the timestamp and only reveal it on hovering over the message? The timestamps take up like 5% of the entire chat which seems excessive.
- Maybe if one user posts multiple messages you can group them into one? Most chats do that now unless there is a large time delay between the messages.

**Comment by klondikemarlen** [comment]
Note to self: double check all font sizes on non-modified browser.
![image](https://user-images.githubusercontent.com/23045206/55298124-abb42380-53e0-11e9-80c7-8fcc015aeb9e.png)

**Comment by klondikemarlen** [comment]
Probably I should just rewrite the chat in Vue with mobile first, dynamic resize with CSS media tags.
Currently it is identical on mobile and desktop but with different navigation controls so it should be an easy transfer.

**Comment by klondikemarlen** [comment]
Also chat input could be changed from text to textarea, so writing in new lines is possible (from Maris)

**Comment by klondikemarlen** [comment]
Add new message count to toggle switch.

Work out how to notify Kingdom vs. Global chat.
