### ISSUE TITLE
End of wars are sometimes crediting wrong nation

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#341]
This one is pissing me off. It's happened 3 weeks in a row. I keep thinking I fixed it and it happens again. You are at war. You attack the other kingdom, take land, and the war ends. But then it says that you lost the war and the other kingdom gets the war point! I can't see what's causing this.

**Comment by klondikemarlen** [comment]
Theoretically fixed in: https://github.com/elthran/UndyingKingdoms/pull/343

Though there may be so stray war code somewhere.
