### ISSUE TITLE
Debugging/Stabilizing development installation script.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#351]
From @Sinan81.
> it might be useful to specify specific version of python during venv creation step:
> 
> ...
> python3 -m venv ~/virtual_envs/udk_env
> ...
> 
> pipenv package enables specifying of Python version in a virtual env like
> 
> pipenv --python 3.6
> 
> See https://docs.pipenv.org/en/latest/basics/

**Comment by klondikemarlen** [comment]
I added python3>=3.6 checking to the install script. I opted not to use pipenv  (which I am unfamiliar with) as it introduces another failure point that I might have to debug.

**Comment by Sinan81** [comment]
on Ubuntu bionic (18.04.1) I had to install Python packages `roman` and `pandas` before the 
`python manage.py reset_db` step which is weird cuz these packages are already indicated in the requirements.txt and must have been installed in the virtual env.

**Comment by klondikemarlen** [comment]
Yeah ... that is weird. I'm actually installing from the setup.py script (I think) and they are listed there too.
I'm going to use Vagrant for testing my script but build the actual install environment with docker.

**Comment by klondikemarlen** [comment]
The basic install script is working. I still have one problem though. I haven't worked out how to safely distribute the front-end build files.

**Comment by Sinan81** [comment]
Awesome! It seems the back-end is now working nicely!

**Comment by klondikemarlen** [comment]
I added a few lines to the install script to clone the remote distribution files (so you don't have to build the front end development environment).
