### ISSUE TITLE
If you have more monsters than lairs, you cant train any troops

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#357]
Reported by 2 players

**Comment by klondikemarlen** [comment]
Working on in https://github.com/elthran/UndyingKingdoms/tree/military2vue

**Comment by klondikemarlen** [comment]
Fixed by @elthran in https://github.com/elthran/UndyingKingdoms/commit/1077e145f114a7e2b1e23dc495b73e82282d8ad9
