### ISSUE TITLE
Download pythonanywhere database as csv file

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#47]
I looked it up and it doesnt seem too complicated. Just a one or two liner of code. However, you are much better at this and can likely figure it out without deleting my database or causing any other headaches. If you can just put the directions on how to do it as a comment in the reset_schema file or something that would be awesome!

**Comment by klondikemarlen** [comment]
1. Start with a basic SQL data dump.
2. Pump the data through a python transform and convert it to .csv.

**Comment by elthran** [comment]
Now it sounds too much like my real job :'(

**Comment by elthran** [comment]
Isn't there just like a one liner that downloads the tables from pythonanywhere as .csv files?

**Comment by klondikemarlen** [comment]
I think you would want to run a daily cron task, which would be a bash and/or python script combo. The script would first do a SQL data dump, then optionally convert to .csv via 50 or so lines of python. If not .sql dump file would probably be fine for a while.
