### ISSUE TITLE
Investiate if trailing slash in url is better or worse

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#58]

**Comment by klondikemarlen** [comment]
It hurts my eyes. :P I personally like the non-trailing style (e.g. https://github.com/elthran/UndyingKingdoms/issues/58) that is used on GitHub among other places.

**Comment by klondikemarlen** [comment]
After much reflect I think we should continue with trailing slash as it is easier to update. You simply tack extra content and routes on after the slash.

**Comment by klondikemarlen** [comment]
I take that back. It doesn't make any difference. Our website should just redirect to whichever one exists.
