### ISSUE TITLE
Have database timestamps be in PST on pythonanywhere

### ISSUE THREAD

**Issue by elthran** [elthran/UndyingKingdoms#61]
Right now locally my database stores in PST but on pythonanywhere the timestamps are all in UTC or something. It makes it hard to read the database and see when things happened or will happen. Can you make it so that the two bases in models/bases.py record their timestamps in PST regardless of the server?

**Comment by klondikemarlen** [comment]
```
import datetime
datetime.datetime.utcnow() + datetime.timedelta(hours=-8)
```

https://medium.com/@nqbao/python-timezone-and-daylight-savings-e511a0093d0
