### ISSUE TITLE
Attacking a county should update theives report.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#72]
When you attack a county your current report of their strength should be updated to include the number of men they lost.

**Comment by elthran** [comment]
I don't think I will add this, at least any time soon. I want to isolate thieves/military. I don't think the thieves page will be affected by military assaults, at least anytime soon. With the new system you can basically spy unlimited times so I think this would add extra complexity for little benefit (ie. if you are about to attack again right after you should be able to estimate how many men died and if you are attacking a few hours later you should be getting a fresh thief report).
