### ISSUE TITLE
Building only occurs when excess resources available?

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#75]
I'm not sure if this is correct or not, but it seems like my buildings are only building when I have enough resources to build them a second time?

i.e.
After building pony stables I have 0 wood. This building didn't build until I had 10 wood in my available resources.
Not sure if this is what is actually happening or not.

**Comment by elthran** [comment]
You purchase buildings when you have supplies available. It is basically buying the materials and stuff. But they won't actually get built until you have available workers. I will explain it more when I set up the game tutorial. Soon I hope to have things like you can have your workers harvest fields and stuff in the spring/autumn, and build buildings in winter, or if you are less intense you can just have cows for dairy. But now I just haven't built the tutorial so its a bit confusing.
