### ISSUE TITLE
Fix weather spam bug.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#8]
When I log in, and multiple days have passed, I get a bunch of weather messages. Only the last one should be displayed.

See example below:
![image](https://user-images.githubusercontent.com/23045206/48633142-8fef3a00-e977-11e8-97de-ac351d31700d.png)

**Comment by elthran** [comment]
Haha I logged in to Github to post this same ticket. Should be an easy fix.
