### ISSUE TITLE
Crowned Ruler Achievement is broken.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#88]
When I created 2 fake accounts to vote for me to crown me the ruler of my county the game crashed.

See:

> 500 Error!!!!!
> 
> Error: (_mysql_exceptions.OperationalError) (1048, "Column 'user_id' cannot be null") [SQL: 'INSERT INTO achievement (time_created, user_id, name, display_title, category, sub_category, description, current_progress, current_tier, maximum_tier, points_rewarded, tier1, tier2, tier3, tier4, tier5) VALUES (CURRENT_TIMESTAMP, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'] [parameters: (None, 2, 'The King is Dead. Long Live the King.', 'Be voted the King during any age of Undying Kingdoms.', None, None, None, 0, 0, 0, None, None, None, None, None)] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by elthran** [comment]
Excellent catch! I will look into it
