### ISSUE TITLE
You can attack yourself.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#89]
This leads to very strange results.

On attack page:
![image](https://user-images.githubusercontent.com/23045206/50745409-d7a77a80-11de-11e9-9b4f-db2c65ad7234.png)

On army page:
![image](https://user-images.githubusercontent.com/23045206/50745415-e1c97900-11de-11e9-9127-afffd1fe570d.png)

**Comment by elthran** [comment]
How did you attack yourself? Was it from typing the url manually or through conventional means?

**Comment by klondikemarlen** [comment]
Typing the URL in manually. But it is kind of an obvious thing to do.

**Comment by klondikemarlen** [comment]
This breaks all attacking until your armies are above zero.

**Comment by elthran** [comment]
hahahaha ok, yes, this is definitely a foreseeable bug. but im not quite sure the best way to deal with it. at least its not urgent

**Comment by klondikemarlen** [comment]
A simple redirect should be fine.

i.e. if /army/2 if id is current_user.county.army.id then redirect to kingdom. Possibly later you could make a page to review your own army?
