### ISSUE TITLE
Change page title to reflect page content.

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#98]
I suggest titles in the form:

Login - Undying Kingdoms
Economy - Undying Kingdoms
ect.

This will require making the page title a Jinja field in layout.html.
```jinja2
<title>{% if title %}{% title %} - Undying Kingdoms{% else %}Undying Kingdoms{% endif %}</title>
```

and to call it
```python
render_template('login.html', title='login')
```

**Comment by klondikemarlen** [comment]
I'm currently doing this in the mobile first version of the site.

in layout.html
`{% block title %}Undying Kingdoms{% endblock %}`

in sub template (overview.html)
`{% title block %}Overview: {{ super() }}{% endblock %}`

**Comment by elthran** [comment]
Will this also update for pc? Or are your changes mobile only?

**Comment by klondikemarlen** [comment]
It would be easy to implement for PC, but right now it is only implemented for mobile.
I think I might update some of the UI for the desktop version soon. At least the login page :P

Basically you just copy that line of code into the top of each file. It should be outside of all other blocks.

**Comment by klondikemarlen** [comment]
Oops should have been: `{% block title %}Overview: {{ super() }}{% endblock %}`
