### ISSUE TITLE
General Game Rebalancing - Suggestions Thread

### ISSUE THREAD

**Issue by klondikemarlen** [elthran/UndyingKingdoms#99]
I suggest changing the cost of a lumber mill to 25 gold, 10 iron.
I also suggest making Dwarf Greybeards cost 10 gold, 3 iron, 0 wood.
I don't know human costs but perhaps they could have a 0 iron unit?.

**Comment by klondikemarlen** [comment]
I suggest that 25 days is too long for thieves to be away? And that the Thieves Guild should change value from 1-5 buildings instead of a percentage of all buildings.

**Comment by klondikemarlen** [comment]
Consider making gold production dependent on employment rather than excess production.
get_gold_change = self.get_tax_income() + self.get_maintenance_workers() * self.tax - self.get_upkeep_costs()

**Comment by elthran** [comment]
Move these to the forum. Our new users are actively discussing these with us
